version: '20.10.8'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=timesheet-spring
    ports:
      - "3308:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone/timesheet-spring?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: ""
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone      